### ISSUE TITLE
Coffee Help returns `Nope`

### ISSUE THREAD

**Issue by elpiel-efuture** [assafgelber/slash-coffee#3]
Today I am typing
`/coffee help`
and the only result that I've got 10 times was
`Nope`
Also any other command is also not working.

**Comment by Chesire** [comment]
I'm seeing this as well unfortunately, not had any commands working

**Comment by assafgelber** [comment]
Sorry for the downtime. Slack requested that I update the verification token but was away on vacation.
Everything should be fixed now, so please re-open if you're still getting this issue.

Thanks for the quick report!
